import os
from dotenv import load_dotenv

# ________________________DATABASE______________________
load_dotenv()  # 讀取 .env 檔案，將其中的鍵值對載入為環境變數
DB_HOST     = os.getenv("DB_HOST")  # 從環境變數取得資料庫主機位址，覆蓋 settings 預設值
DB_PORT     = int(os.getenv("DB_PORT"))  # 從環境變數取得資料庫連線埠號，轉為整數
DB_USER     = os.getenv("DB_USER")  # 從環境變數取得資料庫登入帳號
DB_PASSWORD = os.getenv("DB_PASSWORD")  # 從環境變數取得資料庫登入密碼
DB_DATABASE = os.getenv("DB_DATABASE")  # 從環境變數取得資料庫名稱

# ________________________M.C.__________________________
MC_RCON_HOST = os.getenv("MC_RCON_HOST")
MC_RCON_PORT = int(os.getenv("MC_RCON_PORT"))
MC_RCON_PASSWORD = os.getenv("MC_RCON_PASSWORD")

# ________________________cloudinary______________________
CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")
# # ________________________POOL__________________________
# POOL_NAME = "pool"
# POOL_SIZE = 5
# ________________________IMAGE___________________________


# ________________________BRANCH TABLES_________________
BRANCH_A_TABLE = "user"

BRANCH_B_PRODUCTS_TABLE         = "products"
BRANCH_B_PRODUCT_PICS_TABLE     = "product_pics"
BRANCH_B_PRODUCT_STOCK_TABLE    = "product_stock"

BRANCH_C_CART_TABLE                  = "cart_items"
BRANCH_C_ORDER_TABLE                 = "orders"
BRANCH_C_ORDER_ITEMS_TABLE           = "order_items"
BRANCH_C_ACTIVE_TAG_TABLE            = "active_tag"
BRANCH_C_PENDING_DELIVERIES_TABLE    = "pending_deliveries"

BRANCH_D_MANAGE_LOG_TABLE       = "manage_log"

# ________________________EMAIL_________________________
MAIL_SERVER='smtp.gmail.com'
MAIL_PORT = 465
MAIL_USERNAME = os.getenv("MAIL_USERNAME")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
MAIL_USE_TLS = False
MAIL_USE_SSL = True


CODE_EXPIRE_MINUTES = 5

# ________________________FLASK_________________________
APP_PORT = 7775 # FLASK啟用時所用的埠號 預設為8000 可以自行調整
SESSION_KEY = "MyShoppingAppProject" # 建立SESSION時使用的SESSION KEY
SESSION_AUTHO = "AUTHO" # 用於儲存使用者登入狀態的KEY 各分支會將以此作為判斷使用者是否登入用的依據(整合後才會用到)

# ________________________IMAGE TYPE____________________
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
PROFILE_FOLDER = "profile"
PRODUCT_FOLDER = "product"

PROFILE_DEFAULT_PATH = f"https://res.cloudinary.com/dca1ag2yt/image/upload/v1779814173/static/{PROFILE_FOLDER}/default_profile.png"
PRODUCT_DEFAULT_PATH = f"https://res.cloudinary.com/dca1ag2yt/image/upload/v1779760174/static/{PRODUCT_FOLDER}/default_product.png"
# ________________________ECPay 綠界金流____________________

# 公開測試金鑰（綠界官方文件提供，所有人都能用）：
#   MerchantID = 3002607
#   HashKey    = pwFHCqoQZGmho4w6
#   HashIV     = EkRm7iFT261dpevs
#
# .env 沒設定時會自動 fallback 到公開金鑰，方便快速測試。
# 若想用自己的測試商店，把這三個值寫進 .env 即可。
ECPAY_MERCHANT_ID = "3002607"
ECPAY_HASH_KEY    = "pwFHCqoQZGmho4w6"
ECPAY_HASH_IV     = "EkRm7iFT261dpevs"

# 綠界 AIO 結帳端點：
#   測試環境：https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5
#   正式環境：https://payment.ecpay.com.tw/Cashier/AioCheckOut/V5
ECPAY_AIO_URL = "https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5"

# ngrok 公開網址（綠界 server-to-server callback 需要這個才能打到 localhost）
# 例：NGROK_URL=https://abc123.ngrok-free.app
# 每次重開 ngrok 都會換，記得在 .env 改這個值
NGROK_URL = os.getenv("NGROK_URL", f"http://localhost:{APP_PORT}")

# 本機網址（綠界瀏覽器跳回給使用者看的網址）
# 使用者瀏覽器在 localhost 操作，session cookie 在 localhost domain。
# 如果跳回 ngrok 網址會跨 domain，session 拿不到。
# 所以「OrderResultURL」要用 localhost，但「ReturnURL（server 打的）」維持 ngrok。
LOCAL_URL = f"http://localhost:{APP_PORT}"

# ________________________MC 商品表____________________
MC_PRODUCT_ITEMS = {
    "礦物與素材": {
        "鑽石": "minecraft:diamond",
        "翡翠": "minecraft:emerald",
        "青金石": "minecraft:lapis_lazuli",
        "紅石粉": "minecraft:redstone",
        "煤炭": "minecraft:coal",
        "木炭": "minecraft:charcoal",
        "石英": "minecraft:quartz",
        "燧石": "minecraft:flint",
        "鐵錠": "minecraft:iron_ingot",
        "金錠": "minecraft:gold_ingot",
        "銅錠": "minecraft:copper_ingot",
        "下界合金錠": "minecraft:netherite_ingot",
        "下界合金碎片": "minecraft:netherite_scrap",
        "鐵塊": "minecraft:iron_block",
        "金塊": "minecraft:gold_block",
        "鑽石塊": "minecraft:diamond_block",
        "翡翠塊": "minecraft:emerald_block",
        "青金石塊": "minecraft:lapis_block",
        "紅石塊": "minecraft:redstone_block",
        "綠寶石塊": "minecraft:emerald_block",
        "銅塊": "minecraft:copper_block",
        "下界合金塊": "minecraft:netherite_block",
        "煤炭塊": "minecraft:coal_block",
        "紫水晶碎片": "minecraft:amethyst_shard",
        "紫水晶塊": "minecraft:amethyst_block",
        "芽紫水晶": "minecraft:budding_amethyst",
        "回音碎片": "minecraft:echo_shard",
    },
    "礦石": {
        "鑽石礦石": "minecraft:diamond_ore",
        "深層鑽石礦石": "minecraft:deepslate_diamond_ore",
        "翡翠礦石": "minecraft:emerald_ore",
        "深層翡翠礦石": "minecraft:deepslate_emerald_ore",
        "青金石礦石": "minecraft:lapis_ore",
        "深層青金石礦石": "minecraft:deepslate_lapis_ore",
        "紅石礦石": "minecraft:redstone_ore",
        "深層紅石礦石": "minecraft:deepslate_redstone_ore",
        "煤礦石": "minecraft:coal_ore",
        "深層煤礦石": "minecraft:deepslate_coal_ore",
        "鐵礦石": "minecraft:iron_ore",
        "深層鐵礦石": "minecraft:deepslate_iron_ore",
        "金礦石": "minecraft:gold_ore",
        "深層金礦石": "minecraft:deepslate_gold_ore",
        "銅礦石": "minecraft:copper_ore",
        "深層銅礦石": "minecraft:deepslate_copper_ore",
        "下界金礦石": "minecraft:nether_gold_ore",
        "下界石英礦石": "minecraft:nether_quartz_ore",
        "遠古殘骸": "minecraft:ancient_debris",
    },
    "武器": {
        "木劍": "minecraft:wooden_sword",
        "石劍": "minecraft:stone_sword",
        "鐵劍": "minecraft:iron_sword",
        "金劍": "minecraft:golden_sword",
        "鑽石劍": "minecraft:diamond_sword",
        "下界合金劍": "minecraft:netherite_sword",
        "弓": "minecraft:bow",
        "十字弓": "minecraft:crossbow",
        "三叉戟": "minecraft:trident",
        "箭": "minecraft:arrow",
        "光譜箭": "minecraft:spectral_arrow",
    },
    "工具": {
        "木鎬": "minecraft:wooden_pickaxe",
        "石鎬": "minecraft:stone_pickaxe",
        "鐵鎬": "minecraft:iron_pickaxe",
        "金鎬": "minecraft:golden_pickaxe",
        "鑽石鎬": "minecraft:diamond_pickaxe",
        "下界合金鎬": "minecraft:netherite_pickaxe",
        "木斧": "minecraft:wooden_axe",
        "石斧": "minecraft:stone_axe",
        "鐵斧": "minecraft:iron_axe",
        "金斧": "minecraft:golden_axe",
        "鑽石斧": "minecraft:diamond_axe",
        "下界合金斧": "minecraft:netherite_axe",
        "木鏟": "minecraft:wooden_shovel",
        "石鏟": "minecraft:stone_shovel",
        "鐵鏟": "minecraft:iron_shovel",
        "金鏟": "minecraft:golden_shovel",
        "鑽石鏟": "minecraft:diamond_shovel",
        "下界合金鏟": "minecraft:netherite_shovel",
        "木鋤": "minecraft:wooden_hoe",
        "石鋤": "minecraft:stone_hoe",
        "鐵鋤": "minecraft:iron_hoe",
        "金鋤": "minecraft:golden_hoe",
        "鑽石鋤": "minecraft:diamond_hoe",
        "下界合金鋤": "minecraft:netherite_hoe",
        "釣竿": "minecraft:fishing_rod",
        "打火石": "minecraft:flint_and_steel",
        "剪刀": "minecraft:shears",
        "指南針": "minecraft:compass",
        "時鐘": "minecraft:clock",
        "地圖": "minecraft:map",
        "望遠鏡": "minecraft:spyglass",
        "刷子": "minecraft:brush",
    },
    "盔甲": {
        "皮革頭盔": "minecraft:leather_helmet",
        "皮革胸甲": "minecraft:leather_chestplate",
        "皮革護腿": "minecraft:leather_leggings",
        "皮革靴子": "minecraft:leather_boots",
        "鐵頭盔": "minecraft:iron_helmet",
        "鐵胸甲": "minecraft:iron_chestplate",
        "鐵護腿": "minecraft:iron_leggings",
        "鐵靴子": "minecraft:iron_boots",
        "金頭盔": "minecraft:golden_helmet",
        "金胸甲": "minecraft:golden_chestplate",
        "金護腿": "minecraft:golden_leggings",
        "金靴子": "minecraft:golden_boots",
        "鑽石頭盔": "minecraft:diamond_helmet",
        "鑽石胸甲": "minecraft:diamond_chestplate",
        "鑽石護腿": "minecraft:diamond_leggings",
        "鑽石靴子": "minecraft:diamond_boots",
        "下界合金頭盔": "minecraft:netherite_helmet",
        "下界合金胸甲": "minecraft:netherite_chestplate",
        "下界合金護腿": "minecraft:netherite_leggings",
        "下界合金靴子": "minecraft:netherite_boots",
        "烏龜殼": "minecraft:turtle_helmet",
        "盾牌": "minecraft:shield",
        "鞘翅": "minecraft:elytra",
    },
    "食物": {
        "蘋果": "minecraft:apple",
        "金蘋果": "minecraft:golden_apple",
        "附魔金蘋果": "minecraft:enchanted_golden_apple",
        "麵包": "minecraft:bread",
        "生牛肉": "minecraft:beef",
        "牛排": "minecraft:cooked_beef",
        "生豬肉": "minecraft:porkchop",
        "烤豬排": "minecraft:cooked_porkchop",
        "生羊肉": "minecraft:mutton",
        "烤羊排": "minecraft:cooked_mutton",
        "生雞肉": "minecraft:chicken",
        "烤雞肉": "minecraft:cooked_chicken",
        "生鮭魚": "minecraft:salmon",
        "烤鮭魚": "minecraft:cooked_salmon",
        "生鱈魚": "minecraft:cod",
        "烤鱈魚": "minecraft:cooked_cod",
        "熱帶魚": "minecraft:tropical_fish",
        "河豚": "minecraft:pufferfish",
        "生兔肉": "minecraft:rabbit",
        "烤兔肉": "minecraft:cooked_rabbit",
        "兔肉湯": "minecraft:rabbit_stew",
        "蘑菇燉菜": "minecraft:mushroom_stew",
        "甜菜湯": "minecraft:beetroot_soup",
        "胡蘿蔔": "minecraft:carrot",
        "金胡蘿蔔": "minecraft:golden_carrot",
        "馬鈴薯": "minecraft:potato",
        "烤馬鈴薯": "minecraft:baked_potato",
        "毒馬鈴薯": "minecraft:poisonous_potato",
        "甜菜": "minecraft:beetroot",
        "西瓜片": "minecraft:melon_slice",
        "南瓜派": "minecraft:pumpkin_pie",
        "蛋糕": "minecraft:cake",
        "餅乾": "minecraft:cookie",
        "甜漿果": "minecraft:sweet_berries",
        "發光漿果": "minecraft:glow_berries",
        "蜂蜜瓶": "minecraft:honey_bottle",
        "雞蛋": "minecraft:egg",
    },
    "藥水": {
        "水瓶": "minecraft:potion",
        "再生藥水": "minecraft:potion",
        "迅捷藥水": "minecraft:potion",
        "力量藥水": "minecraft:potion",
        "即效治療藥水": "minecraft:potion",
        "即效傷害藥水": "minecraft:potion",
        "跳躍提升藥水": "minecraft:potion",
        "水中呼吸藥水": "minecraft:potion",
        "隱形藥水": "minecraft:potion",
        "夜視藥水": "minecraft:potion",
        "火焰抵抗藥水": "minecraft:potion",
        "緩降藥水": "minecraft:potion",
        "神龜藥水": "minecraft:potion",
        "噴濺治療藥水": "minecraft:splash_potion",
        "噴濺傷害藥水": "minecraft:splash_potion",
        "噴濺隱形藥水": "minecraft:splash_potion",
        "滯留治療藥水": "minecraft:lingering_potion",
        "滯留傷害藥水": "minecraft:lingering_potion",
    },
    "生成蛋": {
        "苦力怕生成蛋": "minecraft:creeper_spawn_egg",
        "骷髏生成蛋": "minecraft:skeleton_spawn_egg",
        "殭屍生成蛋": "minecraft:zombie_spawn_egg",
        "蜘蛛生成蛋": "minecraft:spider_spawn_egg",
        "洞穴蜘蛛生成蛋": "minecraft:cave_spider_spawn_egg",
        "末影人生成蛋": "minecraft:enderman_spawn_egg",
        "豬人生成蛋": "minecraft:zombified_piglin_spawn_egg",
        "岩漿怪生成蛋": "minecraft:magma_cube_spawn_egg",
        "烈焰人生成蛋": "minecraft:blaze_spawn_egg",
        "凋零骷髏生成蛋": "minecraft:wither_skeleton_spawn_egg",
        "守衛者生成蛋": "minecraft:guardian_spawn_egg",
        "遠古守衛者生成蛋": "minecraft:elder_guardian_spawn_egg",
        "劫掠獸生成蛋": "minecraft:ravager_spawn_egg",
        "掠奪者生成蛋": "minecraft:pillager_spawn_egg",
        "衛道士生成蛋": "minecraft:vindicator_spawn_egg",
        "喚魔者生成蛋": "minecraft:evoker_spawn_egg",
        "女巫生成蛋": "minecraft:witch_spawn_egg",
        "溺屍生成蛋": "minecraft:drowned_spawn_egg",
        "幻翼生成蛋": "minecraft:phantom_spawn_egg",
        "豬布林生成蛋": "minecraft:piglin_spawn_egg",
        "豬布林蠻兵生成蛋": "minecraft:piglin_brute_spawn_egg",
        "疣豬獸生成蛋": "minecraft:hoglin_spawn_egg",
        "殭屍疣豬獸生成蛋": "minecraft:zoglin_spawn_egg",
        "監守者生成蛋": "minecraft:warden_spawn_egg",
        "青蛙生成蛋": "minecraft:frog_spawn_egg",
        "駱駝生成蛋": "minecraft:camel_spawn_egg",
        "嗅探獸生成蛋": "minecraft:sniffer_spawn_egg",
        "犰狳生成蛋": "minecraft:armadillo_spawn_egg",
        "豬生成蛋": "minecraft:pig_spawn_egg",
        "牛生成蛋": "minecraft:cow_spawn_egg",
        "羊生成蛋": "minecraft:sheep_spawn_egg",
        "雞生成蛋": "minecraft:chicken_spawn_egg",
        "馬生成蛋": "minecraft:horse_spawn_egg",
        "驢生成蛋": "minecraft:donkey_spawn_egg",
        "騾生成蛋": "minecraft:mule_spawn_egg",
        "狼生成蛋": "minecraft:wolf_spawn_egg",
        "貓生成蛋": "minecraft:cat_spawn_egg",
        "鸚鵡生成蛋": "minecraft:parrot_spawn_egg",
        "狐狸生成蛋": "minecraft:fox_spawn_egg",
        "熊貓生成蛋": "minecraft:panda_spawn_egg",
        "北極熊生成蛋": "minecraft:polar_bear_spawn_egg",
        "蜜蜂生成蛋": "minecraft:bee_spawn_egg",
        "美西螈生成蛋": "minecraft:axolotl_spawn_egg",
        "山羊生成蛋": "minecraft:goat_spawn_egg",
        "海豚生成蛋": "minecraft:dolphin_spawn_egg",
        "海龜生成蛋": "minecraft:turtle_spawn_egg",
        "魷魚生成蛋": "minecraft:squid_spawn_egg",
        "發光魷魚生成蛋": "minecraft:glow_squid_spawn_egg",
        "蝙蝠生成蛋": "minecraft:bat_spawn_egg",
        "流浪者生成蛋": "minecraft:stray_spawn_egg",
        "殭屍村民生成蛋": "minecraft:zombie_villager_spawn_egg",
        "村民生成蛋": "minecraft:villager_spawn_egg",
        "流浪商人生成蛋": "minecraft:wandering_trader_spawn_egg",
        "羊駝生成蛋": "minecraft:llama_spawn_egg",
        "史萊姆生成蛋": "minecraft:slime_spawn_egg",
        "殭屍馬生成蛋": "minecraft:zombie_horse_spawn_egg",
        "骷髏馬生成蛋": "minecraft:skeleton_horse_spawn_egg",
        "末影龍生成蛋": "minecraft:ender_dragon_spawn_egg",
        "凋零生成蛋": "minecraft:wither_spawn_egg",
        "鐵傀儡生成蛋": "minecraft:iron_golem_spawn_egg",
        "雪傀儡生成蛋": "minecraft:snow_golem_spawn_egg",
    },
    "附魔書": {
        "附魔書": "minecraft:enchanted_book",
    },
    "稀有與特殊": {
        "信標": "minecraft:beacon",
        "龍蛋": "minecraft:dragon_egg",
        "下界之星": "minecraft:nether_star",
        "潮汐核心": "minecraft:heart_of_the_sea",
        "末地傳送門框架": "minecraft:end_portal_frame",
        "基岩": "minecraft:bedrock",
        "屏障": "minecraft:barrier",
        "光源方塊": "minecraft:light",
        "調試棒": "minecraft:debug_stick",
        "知識之書": "minecraft:knowledge_book",
        "指令方塊": "minecraft:command_block",
        "鎖鏈指令方塊": "minecraft:chain_command_block",
        "重複指令方塊": "minecraft:repeating_command_block",
        "結構方塊": "minecraft:structure_block",
        "結構空洞": "minecraft:structure_void",
        "名稱牌": "minecraft:name_tag",
        "鞍": "minecraft:saddle",
        "末影珍珠": "minecraft:ender_pearl",
        "末影眼": "minecraft:ender_eye",
        "末地水晶": "minecraft:end_crystal",
        "凋零骷髏頭": "minecraft:wither_skeleton_skull",
        "苦力怕頭": "minecraft:creeper_head",
        "殭屍頭": "minecraft:zombie_head",
        "骷髏頭": "minecraft:skeleton_skull",
        "玩家頭顱": "minecraft:player_head",
        "龍首": "minecraft:dragon_head",
        "磁石": "minecraft:lodestone",
        "海靈核心": "minecraft:conduit",
        "強化深板岩": "minecraft:reinforced_deepslate",
    },
    "音樂唱片": {
        "音樂唱片11": "minecraft:music_disc_11",
        "音樂唱片13": "minecraft:music_disc_13",
        "音樂唱片cat": "minecraft:music_disc_cat",
        "音樂唱片blocks": "minecraft:music_disc_blocks",
        "音樂唱片chirp": "minecraft:music_disc_chirp",
        "音樂唱片far": "minecraft:music_disc_far",
        "音樂唱片mall": "minecraft:music_disc_mall",
        "音樂唱片mellohi": "minecraft:music_disc_mellohi",
        "音樂唱片stal": "minecraft:music_disc_stal",
        "音樂唱片strad": "minecraft:music_disc_strad",
        "音樂唱片wait": "minecraft:music_disc_wait",
        "音樂唱片ward": "minecraft:music_disc_ward",
        "音樂唱片otherside": "minecraft:music_disc_otherside",
        "音樂唱片pigstep": "minecraft:music_disc_pigstep",
        "音樂唱片5": "minecraft:music_disc_5",
        "音樂唱片relic": "minecraft:music_disc_relic",
    },
    "旗幟圖案": {
        "骷髏旗幟圖案": "minecraft:skull_banner_pattern",
        "苦力怕旗幟圖案": "minecraft:creeper_banner_pattern",
        "磚塊旗幟圖案": "minecraft:brick_banner_pattern",
        "Mojang旗幟圖案": "minecraft:mojang_banner_pattern",
        "花朵旗幟圖案": "minecraft:flower_banner_pattern",
        "球形旗幟圖案": "minecraft:globe_banner_pattern",
        "豬鼻旗幟圖案": "minecraft:piglin_banner_pattern",
    },
    "盔甲紋飾": {
        "盔甲紋飾-哨兵": "minecraft:sentry_armor_trim_smithing_template",
        "盔甲紋飾-沙丘": "minecraft:dune_armor_trim_smithing_template",
        "盔甲紋飾-海岸": "minecraft:coast_armor_trim_smithing_template",
        "盔甲紋飾-荒野": "minecraft:wild_armor_trim_smithing_template",
        "盔甲紋飾-潮汐": "minecraft:tide_armor_trim_smithing_template",
        "盔甲紋飾-眼睛": "minecraft:eye_armor_trim_smithing_template",
        "盔甲紋飾-幽靈": "minecraft:vex_armor_trim_smithing_template",
        "盔甲紋飾-守護": "minecraft:ward_armor_trim_smithing_template",
        "盔甲紋飾-沉默": "minecraft:silence_armor_trim_smithing_template",
        "盔甲紋飾-提升": "minecraft:raiser_armor_trim_smithing_template",
        "盔甲紋飾-主機": "minecraft:host_armor_trim_smithing_template",
        "盔甲紋飾-流動": "minecraft:flow_armor_trim_smithing_template",
        "盔甲紋飾-閃電": "minecraft:bolt_armor_trim_smithing_template",
        "盔甲紋飾-塑形": "minecraft:shaper_armor_trim_smithing_template",
    },
    "建材方塊": {
        "石頭": "minecraft:stone",
        "花崗岩": "minecraft:granite",
        "閃長岩": "minecraft:diorite",
        "安山岩": "minecraft:andesite",
        "圓石": "minecraft:cobblestone",
        "草方塊": "minecraft:grass_block",
        "泥土": "minecraft:dirt",
        "沙子": "minecraft:sand",
        "紅沙": "minecraft:red_sand",
        "礫石": "minecraft:gravel",
        "砂岩": "minecraft:sandstone",
        "紅砂岩": "minecraft:red_sandstone",
        "黑曜石": "minecraft:obsidian",
        "哭泣黑曜石": "minecraft:crying_obsidian",
        "玻璃": "minecraft:glass",
        "冰": "minecraft:ice",
        "包裝冰": "minecraft:packed_ice",
        "藍冰": "minecraft:blue_ice",
        "雪塊": "minecraft:snow_block",
        "黏土塊": "minecraft:clay",
        "深板岩": "minecraft:deepslate",
        "凝灰岩": "minecraft:tuff",
        "方解石": "minecraft:calcite",
        "深板岩磚": "minecraft:deepslate_bricks",
        "鵝卵石深板岩": "minecraft:cobbled_deepslate",
        "石磚": "minecraft:stone_bricks",
        "苔石磚": "minecraft:mossy_stone_bricks",
        "裂石磚": "minecraft:cracked_stone_bricks",
        "下界磚": "minecraft:nether_brick",
        "紅下界磚": "minecraft:red_nether_bricks",
        "石英磚": "minecraft:quartz_block",
        "末地石": "minecraft:end_stone",
        "末地石磚": "minecraft:end_stone_bricks",
        "紫珀柱": "minecraft:purpur_pillar",
        "紫珀塊": "minecraft:purpur_block",
        "海晶石": "minecraft:prismarine",
        "海晶石磚": "minecraft:prismarine_bricks",
        "暗海晶石": "minecraft:dark_prismarine",
        "地獄岩": "minecraft:netherrack",
        "靈魂沙": "minecraft:soul_sand",
        "靈魂土": "minecraft:soul_soil",
        "玄武岩": "minecraft:basalt",
        "光滑玄武岩": "minecraft:smooth_basalt",
        "黑石": "minecraft:blackstone",
        "磨製黑石磚": "minecraft:polished_blackstone_bricks",
        "骨塊": "minecraft:bone_block",
        "南瓜": "minecraft:pumpkin",
        "雕刻南瓜": "minecraft:carved_pumpkin",
        "仙人掌": "minecraft:cactus",
        "竹子": "minecraft:bamboo",
        "蜘蛛網": "minecraft:cobweb",
        "海草": "minecraft:seagrass",
        "乾燥海帶塊": "minecraft:dried_kelp_block",
        "海綿": "minecraft:sponge",
        "濕海綿": "minecraft:wet_sponge",
        "海晶燈": "minecraft:sea_lantern",
        "螢光石": "minecraft:glowstone",
        "蛙明燈": "minecraft:froglight",
        "末端桿": "minecraft:end_rod",
    },
    "木材": {
        "橡木木板": "minecraft:oak_planks",
        "雲杉木板": "minecraft:spruce_planks",
        "白樺木板": "minecraft:birch_planks",
        "叢林木板": "minecraft:jungle_planks",
        "金合歡木板": "minecraft:acacia_planks",
        "深色橡木木板": "minecraft:dark_oak_planks",
        "紅樹木板": "minecraft:mangrove_planks",
        "櫻花木板": "minecraft:cherry_planks",
        "竹木板": "minecraft:bamboo_planks",
        "地獄木木板": "minecraft:crimson_planks",
        "扭曲木木板": "minecraft:warped_planks",
        "橡木原木": "minecraft:oak_log",
        "雲杉原木": "minecraft:spruce_log",
        "白樺原木": "minecraft:birch_log",
        "叢林原木": "minecraft:jungle_log",
        "金合歡原木": "minecraft:acacia_log",
        "深色橡木原木": "minecraft:dark_oak_log",
        "紅樹原木": "minecraft:mangrove_log",
        "櫻花原木": "minecraft:cherry_log",
        "竹塊": "minecraft:bamboo_block",
    },
    "幽匿": {
        "幽匿感測體": "minecraft:sculk_sensor",
        "幽匿催化體": "minecraft:sculk_catalyst",
        "幽匿尖嘯體": "minecraft:sculk_shrieker",
        "幽匿塊": "minecraft:sculk",
    },
    "容器與機器": {
        "箱子": "minecraft:chest",
        "陷阱箱": "minecraft:trapped_chest",
        "末界箱": "minecraft:ender_chest",
        "桶": "minecraft:barrel",
        "熔爐": "minecraft:furnace",
        "高爐": "minecraft:blast_furnace",
        "煙燻爐": "minecraft:smoker",
        "製作台": "minecraft:crafting_table",
        "砧台": "minecraft:anvil",
        "磨石": "minecraft:grindstone",
        "附魔台": "minecraft:enchanting_table",
        "釀造台": "minecraft:brewing_stand",
        "投擲器": "minecraft:dispenser",
        "發射器": "minecraft:dropper",
        "漏斗": "minecraft:hopper",
        "堆肥桶": "minecraft:composter",
        "書架": "minecraft:bookshelf",
        "製圖桌": "minecraft:cartography_table",
        "鍛造台": "minecraft:smithing_table",
        "製箭台": "minecraft:fletching_table",
        "織布機": "minecraft:loom",
        "切石機": "minecraft:stonecutter",
        "蜂巢": "minecraft:beehive",
        "蜂窩": "minecraft:bee_nest",
    },
    "紅石元件": {
        "觀察者": "minecraft:observer",
        "活塞": "minecraft:piston",
        "黏性活塞": "minecraft:sticky_piston",
        "紅石比較器": "minecraft:comparator",
        "紅石中繼器": "minecraft:repeater",
        "紅石火把": "minecraft:redstone_torch",
        "紅石燈": "minecraft:redstone_lamp",
        "動力鐵軌": "minecraft:powered_rail",
        "探測鐵軌": "minecraft:detector_rail",
        "啟動鐵軌": "minecraft:activator_rail",
        "鐵軌": "minecraft:rail",
        "TNT": "minecraft:tnt",
    },
    "交通工具": {
        "礦車": "minecraft:minecart",
        "箱形車": "minecraft:chest_minecart",
        "漏斗礦車": "minecraft:hopper_minecart",
        "TNT礦車": "minecraft:tnt_minecart",
        "橡木船": "minecraft:oak_boat",
        "雲杉船": "minecraft:spruce_boat",
        "白樺船": "minecraft:birch_boat",
        "叢林船": "minecraft:jungle_boat",
        "金合歡船": "minecraft:acacia_boat",
        "深色橡木船": "minecraft:dark_oak_boat",
        "紅樹船": "minecraft:mangrove_boat",
        "櫻花船": "minecraft:cherry_boat",
        "竹筏": "minecraft:bamboo_raft",
    },
    "裝飾與照明": {
        "鐘": "minecraft:bell",
        "燈籠": "minecraft:lantern",
        "靈魂燈籠": "minecraft:soul_lantern",
        "火把": "minecraft:torch",
        "靈魂火把": "minecraft:soul_torch",
        "營火": "minecraft:campfire",
        "靈魂營火": "minecraft:soul_campfire",
        "蠟燭": "minecraft:candle",
        "告示牌": "minecraft:oak_sign",
        "懸掛式告示牌": "minecraft:oak_hanging_sign",
    },
    "混凝土": {
        "白色混凝土": "minecraft:white_concrete",
        "橙色混凝土": "minecraft:orange_concrete",
        "品紅色混凝土": "minecraft:magenta_concrete",
        "淡藍色混凝土": "minecraft:light_blue_concrete",
        "黃色混凝土": "minecraft:yellow_concrete",
        "黃綠色混凝土": "minecraft:lime_concrete",
        "粉紅色混凝土": "minecraft:pink_concrete",
        "灰色混凝土": "minecraft:gray_concrete",
        "淡灰色混凝土": "minecraft:light_gray_concrete",
        "青色混凝土": "minecraft:cyan_concrete",
        "紫色混凝土": "minecraft:purple_concrete",
        "藍色混凝土": "minecraft:blue_concrete",
        "棕色混凝土": "minecraft:brown_concrete",
        "綠色混凝土": "minecraft:green_concrete",
        "紅色混凝土": "minecraft:red_concrete",
        "黑色混凝土": "minecraft:black_concrete",
    },
    "羊毛": {
        "白色羊毛": "minecraft:white_wool",
        "橙色羊毛": "minecraft:orange_wool",
        "品紅色羊毛": "minecraft:magenta_wool",
        "淡藍色羊毛": "minecraft:light_blue_wool",
        "黃色羊毛": "minecraft:yellow_wool",
        "黃綠色羊毛": "minecraft:lime_wool",
        "粉紅色羊毛": "minecraft:pink_wool",
        "灰色羊毛": "minecraft:gray_wool",
        "青色羊毛": "minecraft:cyan_wool",
        "紫色羊毛": "minecraft:purple_wool",
        "藍色羊毛": "minecraft:blue_wool",
        "棕色羊毛": "minecraft:brown_wool",
        "綠色羊毛": "minecraft:green_wool",
        "紅色羊毛": "minecraft:red_wool",
        "黑色羊毛": "minecraft:black_wool",
    },
    "染料": {
        "白色染料": "minecraft:white_dye",
        "橙色染料": "minecraft:orange_dye",
        "品紅色染料": "minecraft:magenta_dye",
        "淡藍色染料": "minecraft:light_blue_dye",
        "黃色染料": "minecraft:yellow_dye",
        "黃綠色染料": "minecraft:lime_dye",
        "粉紅色染料": "minecraft:pink_dye",
        "灰色染料": "minecraft:gray_dye",
        "淡灰色染料": "minecraft:light_gray_dye",
        "青色染料": "minecraft:cyan_dye",
        "紫色染料": "minecraft:purple_dye",
        "藍色染料": "minecraft:blue_dye",
        "棕色染料": "minecraft:brown_dye",
        "綠色染料": "minecraft:green_dye",
        "紅色染料": "minecraft:red_dye",
        "黑色染料": "minecraft:black_dye",
        "墨囊": "minecraft:ink_sac",
        "發光墨囊": "minecraft:glow_ink_sac",
        "骨粉": "minecraft:bone_meal",
        "可可豆": "minecraft:cocoa_beans",
    },
    "農業與植物": {
        "小麥": "minecraft:wheat",
        "小麥種子": "minecraft:wheat_seeds",
        "甜菜種子": "minecraft:beetroot_seeds",
        "南瓜種子": "minecraft:pumpkin_seeds",
        "西瓜種子": "minecraft:melon_seeds",
        "地獄疣": "minecraft:nether_wart",
        "藤蔓": "minecraft:vine",
        "海帶": "minecraft:kelp",
        "珊瑚扇": "minecraft:tube_coral_fan",
        "珊瑚塊": "minecraft:tube_coral_block",
        "紅蘑菇": "minecraft:red_mushroom",
        "棕蘑菇": "minecraft:brown_mushroom",
        "蜂蜜塊": "minecraft:honey_block",
    },
    "雜項素材": {
        "書": "minecraft:book",
        "書與筆": "minecraft:book_and_quill",
        "皮革": "minecraft:leather",
        "紙": "minecraft:paper",
        "棍子": "minecraft:stick",
        "繩子": "minecraft:string",
        "羽毛": "minecraft:feather",
        "骨頭": "minecraft:bone",
        "火藥": "minecraft:gunpowder",
        "腐肉": "minecraft:rotten_flesh",
        "蜘蛛眼": "minecraft:spider_eye",
        "發酵蜘蛛眼": "minecraft:fermented_spider_eye",
        "烈焰棒": "minecraft:blaze_rod",
        "烈焰粉": "minecraft:blaze_powder",
        "幽靈淚": "minecraft:ghast_tear",
        "史萊姆球": "minecraft:slime_ball",
        "兔子腳": "minecraft:rabbit_foot",
        "兔皮": "minecraft:rabbit_hide",
        "海龜鱗甲": "minecraft:scute",
        "犰狳鱗甲": "minecraft:armadillo_scute",
        "龍息": "minecraft:dragon_breath",
        "糖": "minecraft:sugar",
    },
}
